[project]
name = "markupy-htmx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "markupy>=1.4.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
